_BASE_: "./Base_phil_cfg.yaml"
MODEL:
  NAME: "phil_rp_shallow_network_1"
  INPUT_DIM: 10
  DROPOUT: 0.2
  NUM_BLOCKS: 8
  HIDDEN_DIM: 10
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 10
  OUTPUT_DIR: "results/phil_rp/pretraining/"
  TRAIN_ONLY: True
  LOG_INTERVAL: 20
  IS_VALIDATE: True
  VALID_INTERVAL: 4
  SAVE_LAST: True
DATA:
  TRAIN_DATA: "./dataset/phil_rp/synthetic_data/train_sample.npy"
  VALID_DATA: "./dataset/phil_rp/synthetic_data/valid_sample.npy"
  TEST_DATA: "./dataset/phil_rp/synthetic_data/test_sample.npy"
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale,
  PATIENCE: 5
  MILESTONE: [7]
  LR_INIT: 0.01
