NAME: "monthly_k_5_tl_pred"
_BASE_: "../Base_phil_ts_cfg.yaml"
TS_FINE_TUNING:
  START: "2004-12-31"
  END: "2024-11-30"
  DATE_LIST: "./dataset/phil_rp/empirical_ts/num_portfolio_49_freq_M_k_5/rebalance_freq_1M/date_list.csv"
MODEL:
  NAME: "phil_nn_2"
  INPUT_DIM: 10
  DROPOUT: 0.2
TEST:
  LOAD_TODAY_MODEL: True
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 10
  OUTPUT_DIR: "results/phil_rp/fine_tuning"
  TRAIN_ONLY: False
  LOG_INTERVAL: 50
  IS_VALIDATE: True
  VALID_INTERVAL: 3
  LOAD_PRETRAIN: True
  PRETRAINING_PATH: "results/phil_rp/pretraining/main_pretraining.pkl"
  SAVE_LAST: True
DATA:
  FINE_TUNING_MAIN_DATA: "./dataset/phil_rp/empirical_ts/train/main_fine_tuning.npy"
  FINE_TUNING_LOAD_MODE: "refresh"
  TRAIN_DATA_DIR: "./dataset/phil_rp/empirical_ts/num_portfolio_49_freq_M_k_5/rebalance_freq_1M/out_of_sample/train_sample/"
  VALID_DATA_DIR: "./dataset/phil_rp/empirical_ts/num_portfolio_49_freq_M_k_5/rebalance_freq_1M/out_of_sample/valid_sample/"
  TEST_DATA_DIR: "./dataset/phil_rp/empirical_ts/num_portfolio_49_freq_M_k_5/rebalance_freq_1M/out_of_sample/test_sample/"
  TRAIN_DATA: ""
  VALID_DATA: ""
  TEST_DATA: ""
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale
  PATIENCE: 5
  MILESTONE: [5]
  LR_INIT: 0.00001
