NAME: "monthly_k_5_tl_pred"
_BASE_: "../../Base_phil_ts_cfg.yaml"
TS_FINE_TUNING:
  START: "2004-12-31"
  END: "2024-11-30"
  DATE_LIST: "./dataset/FactorModelMain/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M/n_components_5/date_list.csv"
MODEL:
  NAME: "phil_nn_2"
  INPUT_DIM: 10
  DROPOUT: 0.2
TEST:
  LOAD_TODAY_MODEL: True
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 5
  OUTPUT_DIR: "results/FactorModelMain/tl_pred/n_assets_49_freq_1M/n_components_5/phil_nn_2"
  TRAIN_ONLY: False
  LOG_INTERVAL: 50
  IS_VALIDATE: True
  VALID_INTERVAL: 3
  LOAD_PRETRAIN: True
  PRETRAINING_PATH: "results/FactorModelMain/pre_training/n_assets_49/n_components_5/delta_0.01_t_30000_seed_1024/phil_nn_2/main_pretraining.pkl"
  SAVE_LAST: True
DATA:
  FINE_TUNING_MAIN_DATA: "./dataset/phil_rp/empirical_ts/train/main_fine_tuning.npy"
  FINE_TUNING_LOAD_MODE: "refresh"
  TRAIN_DATA_DIR: "./dataset/FactorModelMain/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M/n_components_5/train_sample/"
  VALID_DATA_DIR: "./dataset/FactorModelMain/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M/n_components_5/valid_sample/"
  TEST_DATA_DIR: "./dataset/FactorModelMain/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M/n_components_5/test_sample/"
  TRAIN_DATA: ""
  VALID_DATA: ""
  TEST_DATA: ""
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale
  PATIENCE: 5
  MILESTONE: [5]
  LR_INIT: 5e-5
