_BASE_: "../../Base_phil_cfg.yaml"
MODEL:
  NAME: "phil_rp_model_d_encoder_decoder"
  INPUT_DIM: 10
  DROPOUT: 0.2
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 10
  OUTPUT_DIR: "results/FactorModelMain/pre_training/n_assets_49/n_components_5/delta_0.01_t_450_m_10_seed_1024/phil_rp_model_d_encoder_decoder"
  TRAIN_ONLY: True
  LOG_INTERVAL: 20
  IS_VALIDATE: True
  VALID_INTERVAL: 4
  SAVE_LAST: True
DATA:
  TRAIN_DATA: "./dataset/FactorModelMain/synthetic_data/n_assets_49/n_components_5/delta_0.01_t_450_m_10_seed_1024/train_sample.npy"
  VALID_DATA: "./dataset/FactorModelMain/synthetic_data/n_assets_49/n_components_5/delta_0.01_t_450_m_10_seed_1024/valid_sample.npy"
  TEST_DATA: "./dataset/FactorModelMain/synthetic_data/n_assets_49/n_components_5/delta_0.01_t_450_m_10_seed_1024/test_sample.npy"
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale,
  PATIENCE: 5
  MILESTONE: [5, 7]
