DATA_LOADER:
  NAME: "phil_dataloader"
  TRAIN_BATCH_SIZE: 1024
  NUM_WORKERS: 6
LOSS:
  NAME: "smooth_l1_loss"
SOLVER:
  NAME: "sgd"
  SCHEDULER: "multi_step_scale"
  LR_INIT: 0.001
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  MILESTONE: [100, 120]
DATA:
  TRAIN_DATA: "./dataset/phil_rp/synthetic_data/train_sample.npy"
  VALID_DATA: "./dataset/phil_rp/synthetic_data/valid_sample.npy"
  TEST_DATA: "./dataset/phil_rp/synthetic_data/test_sample.npy"
