_BASE_: "./Base_phil_ts_cfg.yaml"
TS_FINE_TUNING:
  START: "2005-01-01"
  END: "2005-01-31"
  DATE_LIST: "./dataset/phil_rp/empirical_ts/date_list.csv"
MODEL:
  NAME: "phil_nn_2"
  INPUT_DIM: 10
  DROPOUT: 0.2
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 10
  OUTPUT_DIR: "results/phil_rp/fine_tuning"
  TRAIN_ONLY: True
  LOG_INTERVAL: 50
  IS_VALIDATE: False
  VALID_INTERVAL: 5
  LOAD_PRETRAIN: True
  PRETRAINING_PATH: "results/phil_rp/pretraining/main_pretraining.pkl"
DATA:
  FINE_TUNING_MAIN_DATA: "./dataset/phil_rp/empirical_ts/train/main_fine_tuning.npy"
  FINE_TUNING_LOAD_MODE: "refresh"
  TRAIN_DATA_DIR: "./dataset/phil_rp/empirical_ts/train/"
  VALID_DATA_DIR: "./dataset/phil_rp/empirical_ts/valid/"
  TEST_DATA_DIR: "./dataset/phil_rp/empirical_ts/test/"
  TRAIN_DATA: ""
  VALID_DATA: ""
  TEST_DATA: ""
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale
  PATIENCE: 5
  MILESTONE: [3, 8]
  LR_INIT: 0.00001
