NAME: "monthly_k_5_tl_pred"
_BASE_: "../../Base/Base_phil_ts_cfg.yaml"
TS_FINE_TUNING:
  START: "2004-12-31"
  END: "2024-11-30"
  DATE_LIST: "./dataset/FactorModelMainBKFeatures/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M_excess_return/n_components_5/date_list.csv"
MODEL:
  NAME: "phil_rp_model_e_wide_then_sparse"
  INPUT_DIM: 856
  DROPOUT: 0.2
TEST:
  LOAD_TODAY_MODEL: True
TRAIN:
  TRAINER: "PhilNNTrainer"
  MAX_EPOCH: 20
  OUTPUT_DIR: "results/FactorModelMainBKFeatures/pure_dl/n_assets_49_freq_1M_excess_return/n_components_5/phil_rp_model_e_wide_then_sparse"
  TRAIN_ONLY: False
  LOG_INTERVAL: 30
  IS_VALIDATE: True
  VALID_INTERVAL: 2
  LOAD_PRETRAIN: False
  PRETRAINING_PATH: ""
  SAVE_LAST: True
DATA:
  FINE_TUNING_MAIN_DATA: ""
  FINE_TUNING_LOAD_MODE: "refresh"
  TRAIN_DATA_DIR: "./dataset/FactorModelMainBKFeatures/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M_excess_return/n_components_5/train_sample/"
  VALID_DATA_DIR: "./dataset/FactorModelMainBKFeatures/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M_excess_return/n_components_5/valid_sample/"
  TEST_DATA_DIR: "./dataset/FactorModelMainBKFeatures/empirical_dynamic_data/out_of_sample/n_assets_49_freq_1M_excess_return/n_components_5/test_sample/"
  TRAIN_DATA: ""
  VALID_DATA: ""
  TEST_DATA: ""
SOLVER:
  SCHEDULER: "multi_step_scale"  # multi_step_scale
  PATIENCE: 5
  MILESTONE: [8, 12, 16]
  LR_INIT: 5e-3
  RESET_LR: True
